### ISSUE TITLE
ptvsd.enable_attach hangs until a debugger connects

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#545]
## Environment data

- PTVSD version: Master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio:VSC

## Actual behavior

Dead lock when calling `ptvsd.enable_attach`

## Expected  behavior

Should work as it used to.

## Steps to reproduce:
* Enable debugging in python code using `ptvsd.enable_attach()`.
* Start the program
* The program waits at the line `ptvsd.enable_attach()`
* Once you attach `locally from same machine`, then debugger works and code gets executed

@ericsnowcurrently can we review the need for the locks that have been added. We have two places resulting in dead locks.

**Comment by ericsnowcurrently** [comment]
FYI, PR #475 (& friends) is probably related.

**Comment by ericsnowcurrently** [comment]
FYI, #475 is not related after all.

**Comment by karthiknadig** [comment]
Is the resolved by #619? If so please close this.

**Comment by ericsnowcurrently** [comment]
PR #619 is actually unrelated.

**Comment by ericsnowcurrently** [comment]
Note that #509 is pretty closely related.

**Comment by DonJayamanne** [comment]
But this wasn't the case before, we have introduced a change that is causing this. So we need to go back to what we did earlier.

**Comment by DonJayamanne** [comment]
> But this wasn't the case before

It was it? If this scenario isn't a regression then skip that test.

**Comment by ericsnowcurrently** [comment]
See also #448, #502, and #521.

**Comment by ericsnowcurrently** [comment]
@fabioz, do you have any ideas on what we can do here (or what we might be doing wrong)?

Our `enable_attach()` func (`ptvsd.enable_attach()` in ptvsd/attach_server.py) calls `pydevd.settrace()`.  The first time it is called (i.e. when the debugger is initialized), `settrace()` blocks until we send `CMD_RUN` to pydevd.  `ptvsd` sends `CMD_RUN` at the end of the VSC protocol session "handshake" (session-startup message passing), i.e. when we handle `configurationDone` (in ptvsd/wrapper.py).  This means that `enable_attach()` currently blocks until a VSC client connects and steps through the handshake to completion.

The problem is that we don't want `enable_attach()` to block.  We tried working around this by just calling `settrace()` in a separate thread.  However, this didn't work since `settrace()` only applies to the current thread (and future threads), so the original thread does not get debugged.  We then tried taking that further by calling `settrace()` in `ptvsd.wait_for_attach()`, to ensure that debugging is enabled in the original thread.  However, this falls apart if `wait_for_attach()` is never called (it isn't required and often won't be called) or is called from a different thread than where 'enable_attach()` was called.

Here are the possibilities at this point:

* we've misunderstood something, i.e. we're doing it wrong (e.g. we should call `CMD_RUN` immediately); we would fix this
* we could let `enable_attach()` block until attached; the status quo [not really an option]
* we could require `wait_for_attach()` to be called (and in the same thread) [not really an option]
* pydevd could change

As far as pydevd changes go, here are some options:

* allow option to not block in `settrace()` (e.g. if passed, do as much as possible in current thread and do minimal blocking part in a new thread)
* provide a new `settrace_noblock()` to get the same effect
* separate pydevd initialization/startup from registering (enabling debugging for) the current thread; the current `settrace()` would then just be a wrapper that calls those two
* support registering a different thread

**Comment by ericsnowcurrently** [comment]
Also, when we do not pass "host" to `settrace()`, it uses a default.  In effect, even if we run pydevd as a "server", `settrace()` forces a "client" connection (by using a default "host").  We've had to work around this by setting `start_client` to our `start_server` implementation.

**Comment by fabioz** [comment]
@ericsnowcurrently I think https://github.com/Microsoft/ptvsd/pull/628#issuecomment-404243406 answers it (if that's important, you need to issue a `CMD_RUN` before sending breakpoints and when waiting to make sure the attach worked, issue any arbitrary command -- such as a `CMD_LIST_THREADS` and wait for it to be completed -- after making sure you've sent all other needed commands related to breakpoints, etc).

Although note that this is tricky... before the CMD_RUN you still have to issue some other configuration commands such as the os client (and personally, I don't see a good reason to have the debugger in an intermediate state during the `enable_attach` and `wait_for_attach`, so, I'd like to know what's the actual expected behavior here as I'm a bit puzzled on how it should work in the first place and why is that important).

Also, this seems to be repeated in several places, so, can we mark this bug as the de-facto place to have this discussion related to the attach? ;)

**Comment by ericsnowcurrently** [comment]
@fabioz, thanks.  I think we have a solution that will work.

**Comment by ericsnowcurrently** [comment]
FYI, part of the problem is that `ptvsd.enable_attach()` has been non-blocking since it was introduced.  So we can't change it to a blocking operation at this point.

**Comment by ericsnowcurrently** [comment]
I've merged a temporary stopgap, but it isn't a good long-term fix.  Either we need to do some really hacky stuff with sys.settrace (see https://github.com/ericsnowcurrently/ptvsd/tree/fix-545-enable-attach-deadlock), or we need to revert #521 and solve that problem in a different way that doesn't cause `enable_attach()` to block.  FWIW, the former is too fragile and I'm not convinced the latter has a good alternative.

Anyway, I'm handling this over to Don. :)

**Comment by lrstry** [comment]
I'm also running into the issue that ptvsd.wait_for_attach() is blocking. Even using version v5.0.0a12 doesn't fix the issue. I still have to attach a debugger so the main thread can continue.

**Comment by karthiknadig** [comment]
@lrstry `ptvsd.wait_for_attach()` is expected to block. It should be used only when you want to block execution till a debugger is attached. If you want to enable debugging in a non blocking manner, just use `ptvsd.enable_attach`. That should not block execution, and you should be able to attach to the running process.
